/**
 * Generates `packages/core/src/pipeline/glyph_widths.ts`: the advance width of every
 * character Noto Sans covers (Latin, Greek, Cyrillic and Vietnamese; not Devanagari), in
 * regular and bold, so the pipeline can measure label text without a font engine. Both
 * renderers then drop the same labels in collision detection, and the widths match the
 * glyphs MapLibre GL JS uses for styles that name Noto Sans, like the VersaTiles styles.
 *
 * Run with `npx tsx scripts/generate-glyph-widths.ts` after updating `@fontsource/noto-sans`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createCanvas, GlobalFonts } from '@napi-rs/canvas';

const root = resolve(import.meta.dirname, '..');
const fontsource = resolve(root, 'node_modules/@fontsource/noto-sans');
const output = resolve(root, 'packages/core/src/pipeline/glyph_widths.ts');

/** Subsets to measure: every subset but Devanagari, which needs shaping. */
const SUBSETS = [
	'latin',
	'latin-ext',
	'greek',
	'greek-ext',
	'cyrillic',
	'cyrillic-ext',
	'vietnamese',
];
/** Widths are stored in thousandths of an em. */
const UNITS = 1000;

/** The code points of `subset`, from the `unicode-range` of its `@font-face` in fontsource's CSS. */
function codePoints(weight: number): Set<number> {
	const css = readFileSync(resolve(fontsource, `${String(weight)}.css`), 'utf8');
	const result = new Set<number>();
	for (const face of css.split('@font-face').slice(1)) {
		const subset = /noto-sans-([a-z-]+)-\d+-normal\.woff2/.exec(face)?.[1];
		if (!subset || !SUBSETS.includes(subset)) continue;
		const range = /unicode-range:([^;]*)/.exec(face)?.[1] ?? '';
		for (const part of range.split(',')) {
			const [from, to] = part
				.trim()
				.replace(/^U\+/i, '')
				.split('-')
				.map((hex) => parseInt(hex, 16));
			for (let c = from!; c <= (to ?? from!); c++) {
				// Control characters never appear in labels (and NUL cannot be measured).
				if (c >= 0x20 && (c < 0x7f || c > 0x9f)) result.add(c);
			}
		}
	}
	return result;
}

function measure(weight: number): Map<number, number> {
	const family = `NotoSansMeasure${String(weight)}`;
	for (const subset of SUBSETS) {
		GlobalFonts.registerFromPath(
			resolve(fontsource, `files/noto-sans-${subset}-${String(weight)}-normal.woff2`),
			family,
		);
	}
	const ctx = createCanvas(10, 10).getContext('2d');
	ctx.font = `${String(UNITS)}px ${family}`;
	const widths = new Map<number, number>();
	for (const c of [...codePoints(weight)].sort((a, b) => a - b)) {
		// Combining marks and other zero-width characters are kept: they add nothing.
		widths.set(c, Math.round(ctx.measureText(String.fromCodePoint(c)).width));
	}
	return widths;
}

/** Runs of consecutive code points, as `[first code point, ...widths]`, to keep the file small. */
function runs(widths: Map<number, number>): number[][] {
	const result: number[][] = [];
	let run: number[] | undefined;
	let next = -1;
	for (const [c, width] of widths) {
		if (c !== next || !run) {
			run = [c];
			result.push(run);
		}
		run.push(width);
		next = c + 1;
	}
	return result;
}

const table = (weight: number): string =>
	runs(measure(weight))
		.map((run) => `\t[${run.join(',')}],`)
		.join('\n');

writeFileSync(
	output,
	`// Generated by scripts/generate-glyph-widths.ts from Noto Sans (@fontsource/noto-sans). Do not edit.

/** Advance widths in thousandths of an em, as runs: \`[first code point, ...widths]\`. */
export type GlyphWidthRuns = number[][];

/** Noto Sans Regular. */
export const REGULAR: GlyphWidthRuns = [
${table(400)}
];

/** Noto Sans Bold. */
export const BOLD: GlyphWidthRuns = [
${table(700)}
];
`,
);
console.log(`Written ${output}`);
